-Failed tests
Test 1: Teste 1
Test 2: Teste 2
Test 3: Teste 3
-Test 1: Teste 1 (-6.667)
Incorrect program result
 --- Input ---
> 4

 --- Program output ---
>Digite o valor de n:Traceback (most recent call last):
>  File "al8.py", line 5, in <module>
>    while cont>0:
>NameError: name 'cont' is not defined

 --- Expected output (regular expression)---
>.*24.*

-Test 2: Teste 2 (-6.667)
Incorrect program result
 --- Input ---
> 5

 --- Program output ---
>Digite o valor de n:Traceback (most recent call last):
>  File "al8.py", line 5, in <module>
>    while cont>0:
>NameError: name 'cont' is not defined

 --- Expected output (regular expression)---
>.*120.*

-Test 3: Teste 3 (-6.667)
Incorrect program result
 --- Input ---
> 6

 --- Program output ---
>Digite o valor de n:Traceback (most recent call last):
>  File "al8.py", line 5, in <module>
>    while cont>0:
>NameError: name 'cont' is not defined

 --- Expected output (regular expression)---
>.*720.*

-Summary of tests
>+------------------------------+
>|  3 tests run/ 0 tests passed |
>+------------------------------+

