-Failed tests
Test 1: Teste 1
Test 2: Teste 2
Test 3: Teste 3
-Test 1: Teste 1 (-10.000)
Incorrect program result
 --- Input ---
> 2
>4
>3
>2

 --- Program output ---
>digite t1:digite t2:digite t3:digite t4:Traceback (most recent call last):
>  File "tomadas.py", line 8, in <module>
>    print((t1-1)+(t2-1)+(t3-1)+t4)
>NameError: name 't1' is not defined

 --- Expected output (text)---
> '8'

-Test 2: Teste 2 (-10.000)
Incorrect program result
 --- Input ---
> 6
>6
>6
>6

 --- Program output ---
>digite t1:digite t2:digite t3:digite t4:Traceback (most recent call last):
>  File "tomadas.py", line 8, in <module>
>    print((t1-1)+(t2-1)+(t3-1)+t4)
>NameError: name 't1' is not defined

 --- Expected output (text)---
> '21'

-Test 3: Teste 3 (-10.000)
Incorrect program result
 --- Input ---
> 2
>2
>2
>2

 --- Program output ---
>digite t1:digite t2:digite t3:digite t4:Traceback (most recent call last):
>  File "tomadas.py", line 8, in <module>
>    print((t1-1)+(t2-1)+(t3-1)+t4)
>NameError: name 't1' is not defined

 --- Expected output (text)---
> '5'

-Summary of tests
>+------------------------------+
>|  3 tests run/ 0 tests passed |
>+------------------------------+

