-Failed tests
Test 1: Teste 1
Test 2: Teste 2
-Test 1: Teste 1 (-15.000)
Incorrect program result
 --- Input ---
> 10
>4
>1
>2
>3
>4
>5
>6
>7
>8
>9
>10
>5
>9
>18
>20

 --- Program output ---
>Digite a quantidade de a:Digite a quantidade de b:Digite o valor:Digite o valor:Digite o valor:Digite o valor:Digite o valor:Digite o valor:Digite o valor:Digite o valor:Digite o valor:Digite o valor:Digite o valor:Digite o valor:Digite o valor:Digite o valor:Digite a quantidade de a:Traceback (most recent call last):
>  File "contido.py", line 24, in <module>
>    m=int(input('Digite a quantidade de a:'))
>EOFError: EOF when reading a line

 --- Expected output (text)---
> '2'

-Test 2: Teste 2 (-15.000)
Incorrect program result
 --- Input ---
> 7
>5
>22
>11
>10
>8
>12
>76
>50
>5
>9
>76
>20
>21

 --- Program output ---
>Digite a quantidade de a:Digite a quantidade de b:Digite o valor:Digite o valor:Digite o valor:Digite o valor:Digite o valor:Digite o valor:Digite o valor:Digite o valor:Digite o valor:Digite o valor:Digite o valor:Digite o valor:Digite a quantidade de a:Traceback (most recent call last):
>  File "contido.py", line 24, in <module>
>    m=int(input('Digite a quantidade de a:'))
>EOFError: EOF when reading a line

 --- Expected output (text)---
> '1'

-Summary of tests
>+------------------------------+
>|  2 tests run/ 0 tests passed |
>+------------------------------+

