s:1165:"<b>Failed tests</b><br />Test 1: Teste 1
<br />Test 3: Teste 3
<br />Test 6: Teste 6
<br /><b>Test 1: Teste 1 </b><br />Incorrect program result
<br /> --- Input ---
<br /><pre><i> 20
</i></pre>
<br /> --- Program output ---
<br /><pre><i>n:3.59774
</i></pre>
<br /> --- Expected output (text)---
<br /><pre><i> '55.55253'
</i></pre>
<br /><b>Test 3: Teste 3 </b><br />Incorrect program result
<br /> --- Input ---
<br /><pre><i> 2
</i></pre>
<br /> --- Program output ---
<br /><pre><i>n:1.50000
</i></pre>
<br /> --- Expected output (text)---
<br /><pre><i> '2.50000'
</i></pre>
<br /><b>Test 6: Teste 6 </b><br />Incorrect program result
<br /> --- Input ---
<br /><pre><i> -5.87
</i></pre>
<br /> --- Program output ---
<br /><pre><i>n:Traceback (most recent call last):
  File "atividade.py", line 9, in &lt;module&gt;
    for i in range (1,k+1,1):
TypeError: range() integer end argument expected, got float.
</i></pre>
<br /> --- Expected output (text)---
<br /><pre><i> '8.70000'

</i></pre>
<br /><b>Summary of tests</b><br /><pre><i>+------------------------------+
|  6 tests run/ 3 tests passed |
+------------------------------+
</i></pre>
<br /><br />";